name: 'ashby_snowflake'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
models:
  ashby_snowflake:
   
    # Applies to all files under models/staging/
    staging:
      # Materializes all models in staging folder as tables
      materialized: table
      # Persist all models in staging folder in the dbt_staging schema on Snowflake
      # The "STAGING" word is added to the `DEV_DBT` and `DBT` schema names that are defined for Dev and Prod environments, respectively
      +schema: STAGING
      # Applying a "staging" tag to be used by resource selection syntax - e.g. dbt run --select tag:staging
      +tags: staging
      # Setting custom colors for staging nodes (models) for cleaner representation on DAGs
      +docs:
        node_color: "#D4AC0D"
    
    # Apply similar configurations for the "mart" models
    mart:
      materialized: table
      +schema: MART
      +tags: mart
      +docs:
        node_color: "#C0392B"